language: python
python:
  - '3.5'

services: postgresql

intsall: 
  - pip install -r requirements.txt

before_script:
  - psql postgres -c "create user riser with password 'riser';"
  - psql postgres -c "alter user riser createdb;"

script:
  - cd riser && python manage.py migrate
  - python manage.py test

after_success:
  - git tag success
  - git push origin success 

